theme: minima
title: Cedar's Page
author: Cedar Powers
email: cedarmpowers@gmail.com
description: | 
  A small sample of what I get up to in education, economics, and data science! 
  This site is created and maintained by Cedar Powers.
linkedin_username: cedarpowers
github_username: CedarPowers


minima:
  skin: classic
  nav_pages:
    - portfolio.md
    - about.md

